name: Manualy triggered validation
on:
  workflow_dispatch:
    inputs:
      app_link:
        description: 'App link to query'
        required: true
      run_id:
        description: 'Run id of your deployment pipeline'
        required: true
      repo:
        description: 'Repo link'
        required: true
env:
  STATUS_CODE: 0
  CURL_TEST: false

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Run curl on app link
      run: |
        RESULT=$(curl -s -o /dev/null -w "%{response_code}" ${{ github.event.inputs.app_link }})
        echo "STATUS_CODE=$RESULT" >> $GITHUB_ENV
    - name: Verify status code
      if: ${{ env.STATUS_CODE == 200 }}
      run: |
        echo "CURL_TEST=true" >> $GITHUB_ENV
    - name: Display curl test values
      run: |
        echo "Curl test passed: $CURL_TEST"
        echo "Status code: $STATUS_CODE"
    - name: Login to gh
      run: |
        gh auth login --with-token ${{ secrets.GH_TOKEN }}
    - name: Check if workflow ended with success
      run: |
        gh run view ${{ github.event.inputs.run_id }} --exit-status -R {{ github.event.inputs.repo }}