on:
  repository_dispatch:
    types: [deployment-validation]

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo ${{ github.event.client_payload.sha }}
        echo ${{ github.event.client_payload.ref }}