on:
  repository_dispatch:
    types: [deployment-validation]

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Display payload
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}